services:

  postgres:
    image: "postgres:16"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False 
      - PGADMIN_CONFIG_SCRIPT_NAME=/pgadmin
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  bot:
    build: .
    tty: true
    env_file:
      -  .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PYTHONUNBUFFERED=1
      - PORT=8999
    ports:
      - "127.0.0.1:8999:8999"
    volumes:
      - .:/app 
      - ./src/assets:/app/src/assets
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - postgres

  migrations: 
    build: .
    tty: true 
    depends_on:
      - postgres 
    command: ["/bin/sh", "-c", "sleep 5 && poetry run alembic downgrade base && poetry run alembic upgrade head"]

volumes:
  postgres_data:
  pgadmin_data: