services:

  postgres:

    image: "postgres:16"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    tty: true
    env_file:
      -  .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app 
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - postgres

  migrations: 
    build: .
    tty: true 
    depends_on:
      - postgres 

    command: ["/bin/sh", "-c", "sleep 5 && poetry run alembic downgrade base && poetry run alembic upgrade head"]


volumes:
  postgres_data: